/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_aio_flotavehiculos.Vistas;

import java.awt.Color;
import java.awt.event.ActionListener;

/**
 *
 * @author Jesus
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MiVistaJesus
     */
    public PantallaPrincipal() {
        initComponents();
        this.setTitle("AIO Flota de Vehículos");
        this.setLocationRelativeTo(null);
        
    }
    /**
    * Control para escuchar Añadir.
    */
 public void addActionListenerAñadir(ActionListener l){
        Añadir.addActionListener(l);
    }
  /**
    * Control para escuchar Borrar.
    */
 public void addActionListenerBorrar(ActionListener l){
        Borrar.addActionListener(l);
    }
  /**
    * Control para escuchar Modificar.
    */
 public void addActionListenerModificar(ActionListener l){
        Modificar.addActionListener(l);
    }
  /**
    * Control para escuchar Ajustes.
    */
 public void addActionListenerAjustes(ActionListener l){
        Ajustes.addActionListener(l);
    }
 /**
    * Control para actualizar el nombre de usuario en el area de Texto de NOmbre Usuario.
    */
 
 public void setNombreusuario(String nombreusuario) {
        txtNombreUsuario.setText(nombreusuario);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        txtNombreUsuario = new javax.swing.JTextField();
        jPanelCentral = new javax.swing.JPanel();
        jLabelICono = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuOpciones = new javax.swing.JMenu();
        Añadir = new javax.swing.JMenuItem();
        Borrar = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenuItem();
        jMenuAjustes = new javax.swing.JMenu();
        Ajustes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pantalla Principal");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(600, 400));

        txtNombreUsuario.setBackground(new java.awt.Color(0, 102, 153));
        txtNombreUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreUsuario.setText("Bienvenid@:");
        getContentPane().add(txtNombreUsuario, java.awt.BorderLayout.PAGE_END);

        jPanelCentral.setForeground(new java.awt.Color(255, 255, 255));

        jLabelICono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aio.png"))); // NOI18N
        jPanelCentral.add(jLabelICono);

        getContentPane().add(jPanelCentral, java.awt.BorderLayout.CENTER);

        jMenuOpciones.setText("Opciones");

        Añadir.setText("Añadir Vehiculo");
        jMenuOpciones.add(Añadir);

        Borrar.setText("Borrar Vehiculo");
        jMenuOpciones.add(Borrar);

        Modificar.setText("Modificar Vehiculo");
        jMenuOpciones.add(Modificar);

        jMenuBar1.add(jMenuOpciones);

        jMenuAjustes.setText("Ajustes");

        Ajustes.setText("Ir a Ajustes");
        jMenuAjustes.add(Ajustes);

        jMenuBar1.add(jMenuAjustes);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Ajustes;
    private javax.swing.JMenuItem Añadir;
    private javax.swing.JMenuItem Borrar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JLabel jLabelICono;
    private javax.swing.JMenu jMenuAjustes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuOpciones;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}

