/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_aio_flotavehiculos;

/**
 *
 * @author Jesus
 */
public class MiVistaJesus extends javax.swing.JFrame {

    /**
     * Creates new form MiVistaJesus
     */
    public MiVistaJesus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etqTitulo = new javax.swing.JLabel();
        etqImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etqTitulo.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        etqTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etqTitulo.setText("AIO");
        getContentPane().add(etqTitulo, java.awt.BorderLayout.PAGE_END);

        etqImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aiologo.png"))); // NOI18N
        getContentPane().add(etqImagen, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etqImagen;
    private javax.swing.JLabel etqTitulo;
    // End of variables declaration//GEN-END:variables
}
